import os
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

desktop = os.path.join(os.environ["USERPROFILE"], "Desktop")
doc = Document()

style = doc.styles["Normal"]
style.font.name = "Microsoft YaHei"
style.font.size = Pt(11)

def h1(text):
    h = doc.add_heading(text, level=1)
    for r in h.runs:
        r.font.color.rgb = None

def h2(text):
    doc.add_heading(text, level=2)

def p(text):
    doc.add_paragraph(text)

def img_placeholder(caption):
    para = doc.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = para.add_run(f"[ 请在此处粘贴截图: {caption} ]")
    run.font.size = Pt(9)
    run.font.color.rgb = None

# ====== Document ======
h1("DNF Robot 部署启动器 - 新手图文教程")

h2("1. 系统概述")
p("本系统用于管理 DNF 私服的假人机器人。主要由两部分组成：")
p("  - robot 假人程序：运行在 CentOS VM 上，管理假人上线/移动/喊话/摆摊")
p("  - 部署启动器（部署.exe）：Windows GUI 工具，一键部署/重启 robot 并启动游戏服务")
p("VM 连接信息：IP 192.168.200.131  |  SSH root/123456  |  Web 密码 twadmin")

h2("2. 虚拟机准备")
p("2.1 启动 VMware 中的 CentOS VM，确保可以 ping 通 192.168.200.131。")
p("2.2 准备部署文件，将以下两个文件放在同一文件夹中：")
p("    D:\\deploy\\")
p("       ├── 部署.exe      ← 部署启动器")
p("       └── robot         ← 假人控制程序")

h2("3. 部署启动器界面")
img_placeholder("图1 - 部署启动器主界面")
p("双击 部署.exe 打开主界面，界面分为三部分：")
p("  顶部 - SSH 连接配置（主机/用户/密码，默认已填好）")
p("  中部 - 三个操作按钮")
p("  底部 - 实时日志输出区")
p("")
p("三个按钮功能说明：")
p("")
p("  [部署 robot]")
p("    上传 robot → 校验文件大小 → chmod 加权限 → 备份旧版 →")
p("    停止旧进程 → 替换 → 启动新进程 → 验证进程存活")
p("    适用场景：更新了 robot 程序，或首次部署")
p("")
p("  [重启 robot]")
p("    停止旧进程 → 启动新进程")
p("    不上传不替换，适合 robot 卡住/异常时快速重启")
p("")
p("  [启动 /root/run]")
p("    后台执行游戏服务启动脚本 /root/run")
p("    自动等待 df_game_r 进程稳定后检测端口监听")
p("    所有游戏端口就绪后弹窗提示")
p("    适用场景：游戏服务挂了、VM 重启后")

h2("4. 首次部署完整流程")
p("4.1 启动部署启动器（双击 部署.exe）")
img_placeholder("图2 - 部署启动器刚打开的样子")
p("")
p("4.2 点击 [部署 robot]")
p("  日志区会逐步显示：")
p("    [08:00:01] 本地 robot: ... (xxx bytes)")
p("    [08:00:01] SSH 192.168.200.131 连接成功")
p("    [08:00:02] 上传 /root/robot.new 完成")
p("    [08:00:02] 文件大小校验通过 (xxx bytes)")
p("    [08:00:02] chmod +x 完成")
p("    [08:00:02] 备份旧 robot → /root/robot.bak.xxx")
p("    [08:00:03] 旧 robot 已停止")
p("    [08:00:03] 替换 robot 完成")
p("    [08:00:05] 新 robot 已启动 (pid: xxxx)")
p("  最后弹窗: 部署成功")
img_placeholder("图3 - 部署成功弹窗")
p("")
p("4.3 点击 [启动 /root/run]")
p("  日志区会逐步显示：")
p("    [08:00:06] SSH 连接成功，正在启动游戏服务 ...")
p("    [08:00:06] /root/run 已提交，开始监控 ...")
p("    [08:00:12] df_game_r 进程已稳定 (2 个)，等待端口就绪 ...")
p("    [08:00:18] 游戏端口 10011 已监听")
p("    [08:00:20] 游戏端口 10056 已监听")
p("  最后弹窗: 启动成功 - 游戏服务已完全启动！")
img_placeholder("图4 - 启动成功弹窗")

h2("5. Web 管理页面")
p("浏览器打开 http://192.168.200.131:8112，输入密码 twadmin 登录。")
img_placeholder("图5 - Web 管理页面登录后")
p("")
p("5.1 顶部状态卡片")
p("  登录后首行是一排状态卡片，全部绿色表示一切正常：")
p("    Robot    - robot 进程状态")
p("    Database - MySQL 连接（d_taiwan / d_starsky 等）")
p("    Key      - 游戏加密密钥状态")
p("    Game Port- 游戏端口（默认 10011）")
p("    Monitor  - 喊话服务（30303）")
p("")
p("5.2 核心操作区")
p("  Auto 面板:")
p("    设置目标在线人数（例: 100）→ 点 Start → 假人自动上线")
p("    调度会自动控制上线速度、分配 actor、维护目标人数")
p("")
p("  Online / Move / Shout / Store / Logout:")
p("    对选中的假人执行单次操作")
p("    在线/移动/喊话/摆摊/下线")
p("")
p("  Cleanup:")
p("    删除损坏的假人数据")
p("    注意：只用于异常 UID，不要用来代替正常下线")
p("")
p("  Config:")
p("    修改行为配置，如出生点、摆摊物品等")

h2("6. VM 内文件结构")
p("  /root/robot                      robot 主程序")
p("  /root/run                        启动游戏服务脚本")
p("  /root/stop                       停止游戏服务脚本")
p("  /root/robot.bak.*                历史版本自动备份（保留3个）")
p("  /root/robot_stdout.log           robot 启动与 Web 诊断日志")
p("  /root/config/config.ini          主配置")
p("  /root/config/robot_config.ini    行为配置")
p("  /root/config/log_robot           假人业务日志")
p("  /home/neople/game/               DNF 游戏服务目录")

h2("7. 注意事项")
p("  1. 首次部署前确保 VM 已启动，能 ping 通 192.168.200.131")
p("  2. Web 管理页面密码默认为 twadmin，不要修改")
p("  3. 如果网页打不开，检查 robot 进程是否存活")
p("  4. 部署 robot 会自动备份旧版本（保留最近 3 个），路径 /root/robot.bak.*")
p("  5. Cleanup 只用于清理损坏的假人数据，不要替代正常下线")
p("  6. 自动模  式下，手动操作未接管的假人会返回 uid_not_attached")
p("  7. VM CPU 长时间异常时，检查 vmtoolsd 进程（正常应 <3%）")
p("  8. 不要手工修改 /root/config/robot_config.ini 的 [system] 段")
p("  9. 不要用 Cleanup 代替正常下线或缩容")
p("  10. 遇到奇怪问题，先点 [重启 robot] 试试")

h2("8. 常见问题")
p("  Q: 部署后假人不上线？")
p("  A: 先点 [启动 /root/run] 等游戏端口就绪，然后 Web 里点 Auto Start。")
p("")
p("  Q: 网页打不开（192.168.200.131:8112）？")
p("  A: SSH 到 VM 执行 pgrep -af robot 检查进程。没活就点 [重启 robot]。")
p("")
p("  Q: 部署时提示旧进程未停止？")
p("  A: 不影响，程序会警告后继续部署。僵尸进程需要重启 VM 才能清除。")
p("")
p("  Q: 端口检测显示数量和 df_game_r 进程数不一致？")
p("  A: 正常的。有些 df_game_r 是内部通信进程不绑定端口。")
p("")
p("  Q: 三个按钮都点不了？")
p("  A: 检查 SSH 连接信息三栏不能为空。确认 VM 的 22 端口能连通。")
p("")
p("  Q: 日志里出现很多 online_confirm_timeout？")
p("  A: 假人登录超时。可能是目标在线人数太多，游戏服处理不过来。降低目标人数再试。")

# Save
output = os.path.join(desktop, "DNF_Robot_新手教程.docx")
doc.save(output)
print(f"DONE: {output}")
